[package]
name = "spark-rs"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
omit-default-module-path = true

[features]
default = ["antisplat", "ksplat", "ply", "rad", "sogs", "spz", "csplat", "gsplat", "tiny_lod", "bhatt_lod"]
antisplat = ["spark-lib/antisplat"]
ksplat = ["spark-lib/ksplat"]
ply = ["spark-lib/ply"]
rad = ["spark-lib/rad"]
sogs = ["spark-lib/sogs"]
spz = ["spark-lib/spz"]
csplat = ["spark-lib/csplat"]
gsplat = ["spark-lib/gsplat"]
tiny_lod = ["spark-lib/tiny_lod"]
bhatt_lod = ["spark-lib/bhatt_lod"]

[dependencies]
ahash.workspace = true
anyhow.workspace = true
glam.workspace = true
half.workspace = true
js-sys.workspace = true
ordered-float.workspace = true
smallvec.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Window", "Performance"] }
spark-lib = { path = "../spark-lib", default-features = false, features = [] }
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
serde.workspace = true
itertools.workspace = true
console_error_panic_hook = "0.1"
